// IPC 通道名单源 —— main 和 preload 的唯一契约源。
//
// 依据 CLAUDE.md §1.3 契约单源:通道名是 main↔preload 的 wire contract,
// 此前两边各写一遍字符串字面量(加通道改两处,忘改 preload = invoke 静默失败,
// 拼错 = 运行时才能发现)。现收敛为一份常量地图:
// - 拼错/遗漏 = tsc 编译错,不再是运行时静默失败
// - 加通道只改这一处,main/preload 都从本地图取
// 覆盖两类 wire:invoke 请求通道(ipcMain.handle/ipcRenderer.invoke)与
// push 推送通道(webContents.send/ipcRenderer.on)。落位 shell 而非 domain/
// gateway:通道名是 Electron IPC 细节,两个消费方都在 shell,物理最近即对的层。
export const IPC = {
  config: {
    all: "config:all",
    get: "config:get",
    set: "config:set",
  },
  configFile: {
    clearProject: "config-file:clearProject",
    get: "config-file:get",
    getLayered: "config-file:getLayered",
    getProject: "config-file:getProject",
    set: "config-file:set",
    setProject: "config-file:setProject",
  },
  dialog: {
    openDirectory: "dialog:openDirectory",
    openImages: "dialog:openImages",
  },
  extension: {
    disable: "extension:disable",
    enable: "extension:enable",
    install: "extension:install",
    installProgress: "extension:install-progress",
    list: "extension:list",
    remove: "extension:remove",
    reorder: "extension:reorder",
    update: "extension:update",
  },
  fs: {
    listDir: "fs:listDir",
    removePath: "fs:removePath",
    readDirTree: "fs:readDirTree",
    readFile: "fs:readFile",
    createFile: "fs:createFile",
    createDir: "fs:createDir",
    renamePath: "fs:renamePath",
    copyPath: "fs:copyPath",
  },
  git: {
    fileContent: "git:fileContent",
    fileDiff: "git:fileDiff",
    status: "git:status",
    log: "git:log",
    commit: "git:commit",
    push: "git:push",
  },
  llm: {
    oneshot: "llm:oneshot",
  },
  i18n: {
    detect: "i18n:detect",
    list: "i18n:list",
    resources: "i18n:resources",
  },
  kernel: {
    install: "kernel:install",
    installDone: "kernel:install-done",
    installProgress: "kernel:install-progress",
    listVersions: "kernel:listVersions",
    status: "kernel:status",
    toolgateAvailable: "kernel:toolgateAvailable",
  },
  misc: {
    openFile: "open-file",
    revealPath: "reveal-path",
  },
  models: {
    get: "models:get",
    set: "models:set",
  },
  piSettings: {
    get: "pi-settings:get",
    schema: "pi-settings:schema",
    set: "pi-settings:set",
  },
  plugin: {
    unloaded: "plugin:unloaded",
  },
  plugins: {
    changed: "plugins:changed",
    disable: "plugins:disable",
    enable: "plugins:enable",
    install: "plugins:install",
    list: "plugins:list",
    loadFailed: "plugins:loadFailed",
    reload: "plugins:reload",
    uninstall: "plugins:uninstall",
  },
  prefs: {
    get: "prefs:get",
    set: "prefs:set",
  },
  restart: {
    pendingSessions: "restart:pendingSessions",
    restart: "restart:restart",
    restartAllIdle: "restart:restartAllIdle",
    state: "restart:state",
  },
  session: {
    abort: "session:abort",
    abortBash: "session:abortBash",
    abortRetry: "session:abortRetry",
    clone: "session:clone",
    compact: "session:compact",
    copySession: "session:copySession",
    cycleModel: "session:cycleModel",
    cycleThinkingLevel: "session:cycleThinkingLevel",
    delete: "session:delete",
    event: "session:event",
    exportHtml: "session:exportHtml",
    extensionUI: "session:extensionUI",
    followUp: "session:followUp",
    fork: "session:fork",
    getForkMessages: "session:getForkMessages",
    getLastAssistantText: "session:getLastAssistantText",
    getModels: "session:getModels",
    getSnapshot: "session:getSnapshot",
    getStats: "session:getStats",
    getThinkingLevels: "session:getThinkingLevels",
    kernelEvent: "session:kernelEvent",
    open: "session:open",
    prompt: "session:prompt",
    readToolConfig: "session:readToolConfig",
    rename: "session:rename",
    replyExtensionUI: "session:replyExtensionUI",
    runBash: "session:runBash",
    setAutoCompaction: "session:setAutoCompaction",
    setAutoRetry: "session:setAutoRetry",
    setContext: "session:setContext",
    setFollowUpMode: "session:setFollowUpMode",
    setModel: "session:setModel",
    setSteeringMode: "session:setSteeringMode",
    setThinkingLevel: "session:setThinkingLevel",
    snapshot: "session:snapshot",
    start: "session:start",
    steer: "session:steer",
    stop: "session:stop",
    sync: "session:sync",
    testModel: "session:testModel",
    updateHeader: "session:updateHeader",
  },
  sessions: {
    list: "sessions:list",
    recentSettings: "sessions:recentSettings",
    projectStats: "sessions:projectStats",
  },
  settings: {
    changed: "settings:changed",
    list: "settings:list",
  },
  skills: {
    addPath: "skills:addPath",
    changed: "skills:changed",
    getBundled: "skills:getBundled",
    getSourcePaths: "skills:getSourcePaths",
    list: "skills:list",
    removePath: "skills:removePath",
    setBundledEnabled: "skills:setBundledEnabled",
    toggle: "skills:toggle",
    toggleForce: "skills:toggleForce",
    unwatch: "skills:unwatch",
    watch: "skills:watch",
  },
  slots: {
    mainView: "slots:mainView",
    sidePanel: "slots:sidePanel",
    sidebar: "slots:sidebar",
    titlebar: "slots:titlebar",
    fileActions: "slots:fileActions",
  },
  themes: {
    build: "themes:build",
    list: "themes:list",
    systemChanged: "themes:systemChanged",
  },
} as const;

/** 所有合法通道名的联合类型(invoke 应答与 push 推送的总集)。 */
export type IpcChannel =
  { [K in keyof typeof IPC]: (typeof IPC)[K][keyof (typeof IPC)[K]] }[keyof typeof IPC];
