export type SidepanelStyle = "default" | "card" | "minimal" | "outline" | "glass";

export interface SidepanelStylePreset {
  id: SidepanelStyle;
  label: string;
  vars: Record<string, string>;
}

export const PANEL_TOKEN_KEYS = [
  "sidepanel.header.py",
  "sidepanel.header.px",
  "sidepanel.header.border",
  "sidepanel.header.bg",
  "sidepanel.header.bg.hover",
  "sidepanel.header.fs",
  "sidepanel.header.fw",
  "sidepanel.content.py",
  "sidepanel.content.px",
  "sidepanel.icon.btn.size",
  "sidepanel.icon.btn.radius",
  "sidepanel.icon.btn.bg",
  "sidepanel.icon.btn.bg.hover",
  "sidepanel.icon.btn.bg.active",
  "sidepanel.icon.btn.border",
  "sidepanel.icon.active.indicator",
  "sidepanel.icon.gap",
  "sidepanel.icon.size",
  "sidepanel.divider.display",
  "sidepanel.divider.color",
  "sidepanel.row.py",
  "sidepanel.row.px",
  "sidepanel.row.gap",
  "sidepanel.row.bg",
  "sidepanel.row.bg.hover",
  "sidepanel.row.bg.active",
  "sidepanel.row.border",
  "sidepanel.row.border.hover",
  "sidepanel.row.border.active",
  "sidepanel.row.radius",
  "sidepanel.row.shadow",
  "sidepanel.row.shadow.active",
  "sidepanel.toolbar.py",
  "sidepanel.toolbar.px",
  "sidepanel.toolbar.gap",
  "sidepanel.toolbar.border",
  "sidepanel.toolbar.bg",
  "sidepanel.btn.size",
  "sidepanel.btn.radius",
  "sidepanel.btn.border",
  "sidepanel.btn.bg",
  "sidepanel.btn.bg.hover",
  "sidepanel.btn.icon.size",
  "sidepanel.input.py",
  "sidepanel.input.px",
  "sidepanel.input.border",
  "sidepanel.input.border.focus",
  "sidepanel.input.radius",
  "sidepanel.input.bg",
  "sidepanel.card.py",
  "sidepanel.card.px",
  "sidepanel.card.border",
  "sidepanel.card.radius",
  "sidepanel.card.shadow",
  "sidepanel.card.bg",
  "sidepanel.section.fs",
  "sidepanel.section.py",
  "sidepanel.section.px",
  "sidepanel.section.weight",
  "sidepanel.stat.py",
  "sidepanel.glass.blur",
] as const;

export const PANEL_TOKEN_DEFAULTS: Record<string, string> = {
  "sidepanel.header.py": "8px",
  "sidepanel.header.px": "12px",
  "sidepanel.header.border": "1px solid var(--color-border)",
  "sidepanel.header.bg": "transparent",
  "sidepanel.header.bg.hover": "var(--color-surface)",
  "sidepanel.header.fs": "var(--font-size-sm)",
  "sidepanel.header.fw": "500",
  "sidepanel.content.py": "8px",
  "sidepanel.content.px": "10px",
  "sidepanel.icon.btn.size": "36px",
  "sidepanel.icon.btn.radius": "var(--radius-sm)",
  "sidepanel.icon.btn.bg": "transparent",
  "sidepanel.icon.btn.bg.hover": "var(--color-surface)",
  "sidepanel.icon.btn.bg.active": "var(--color-surface)",
  "sidepanel.icon.btn.border": "none",
  "sidepanel.icon.active.indicator": "3px solid var(--color-primary)",
  "sidepanel.icon.gap": "6px",
  "sidepanel.icon.size": "20px",
  "sidepanel.divider.display": "flex",
  "sidepanel.divider.color": "var(--divider-color)",
  "sidepanel.row.py": "4px",
  "sidepanel.row.px": "8px",
  "sidepanel.row.gap": "6px",
  "sidepanel.row.bg": "transparent",
  "sidepanel.row.bg.hover": "var(--color-surface)",
  "sidepanel.row.bg.active": "var(--color-surface)",
  "sidepanel.row.border": "none",
  "sidepanel.row.border.hover": "none",
  "sidepanel.row.border.active": "none",
  "sidepanel.row.radius": "var(--radius-sm)",
  "sidepanel.row.shadow": "none",
  "sidepanel.row.shadow.active": "none",
  "sidepanel.toolbar.py": "4px",
  "sidepanel.toolbar.px": "8px",
  "sidepanel.toolbar.gap": "6px",
  "sidepanel.toolbar.border": "none",
  "sidepanel.toolbar.bg": "transparent",
  "sidepanel.btn.size": "22px",
  "sidepanel.btn.radius": "var(--radius-sm)",
  "sidepanel.btn.border": "none",
  "sidepanel.btn.bg": "transparent",
  "sidepanel.btn.bg.hover": "var(--color-surface)",
  "sidepanel.btn.icon.size": "14px",
  "sidepanel.input.py": "4px",
  "sidepanel.input.px": "8px",
  "sidepanel.input.border": "1px solid var(--color-border)",
  "sidepanel.input.border.focus": "1px solid var(--color-primary)",
  "sidepanel.input.radius": "var(--radius-sm)",
  "sidepanel.input.bg": "var(--color-bg)",
  "sidepanel.card.py": "12px",
  "sidepanel.card.px": "12px",
  "sidepanel.card.border": "1px solid var(--color-border)",
  "sidepanel.card.radius": "var(--radius-md)",
  "sidepanel.card.shadow": "var(--shadow-sm)",
  "sidepanel.card.bg": "var(--color-surface)",
  "sidepanel.section.fs": "var(--font-size-sm)",
  "sidepanel.section.py": "6px",
  "sidepanel.section.px": "8px",
  "sidepanel.section.weight": "600",
  "sidepanel.stat.py": "4px",
  "sidepanel.glass.blur": "none",
};
