// 通道名单源(web-service-architecture.md §6.3)——wire contract 的常量地图。
//
// 原在 api/preload/ipc-channels.ts(Electron IPC 细节);去 IPC 后它是「对接契约清单」:
// 用户服务端按此 channel 清单对接,不加前缀、不改语义。invoke 请求通道(ipcMain.handle/
// ipcRenderer.invoke → gateway.register/wsTransport.invoke)与 push 推送通道
// (webContents.send/ipcRenderer.on → gateway.broadcast/wsTransport.on)。
//
// 落位 core/domain:channel 名是壳与客户端之间的稳定契约,不依赖 Electron/WS——拼错/遗漏
// = tsc 编译错,加通道只改这一处。依赖只向内:本文件零依赖,只被 core/application + api 引用。
export const IPC = {
  app: {
    info: "app:info",
    restart: "app:restart",
  },
  bus: {
    status: "bus:status",
    send: "bus:send",
    sessionCreate: "bus:sessionCreate",
    sessionAbort: "bus:sessionAbort",
    channelMember: "bus:channelMember",
    tapStart: "bus:tapStart",
    tapStop: "bus:tapStop",
    event: "bus:event",
  },
  config: {
    all: "config:all",
    get: "config:get",
    getScope: "config:getScope",
    set: "config:set",
  },
  configFile: {
    append: "config-file:append",
    clearProject: "config-file:clearProject",
    get: "config-file:get",
    getLayered: "config-file:getLayered",
    getProject: "config-file:getProject",
    readBinary: "config-file:readBinary",
    set: "config-file:set",
    setProject: "config-file:setProject",
    writeBinary: "config-file:writeBinary",
  },
  dialog: {
    openDirectory: "dialog:openDirectory",
    openImages: "dialog:openImages",
    openTextFile: "dialog:openTextFile",
    saveTextFile: "dialog:saveTextFile",
    saveZip: "dialog:saveZip",
    openZip: "dialog:openZip",
    writeImages: "dialog:writeImages",
  },
  kernelExtensions: {
    disable: "kernel-extensions:disable",
    enable: "kernel-extensions:enable",
    install: "kernel-extensions:install",
    installProgress: "kernel-extensions:install-progress",
    list: "kernel-extensions:list",
    uninstall: "kernel-extensions:uninstall",
  },
  fonts: {
    list: "fonts:list",
  },
  fs: {
    listDir: "fs:listDir",
    removePath: "fs:removePath",
    readDirTree: "fs:readDirTree",
    readFile: "fs:readFile",
  readFileBase64: "fs:readFileBase64",
    createFile: "fs:createFile",
    createDir: "fs:createDir",
    renamePath: "fs:renamePath",
    copyPath: "fs:copyPath",
  },
  git: {
    fileContent: "git:fileContent",
    fileDiff: "git:fileDiff",
    status: "git:status",
    log: "git:log",
    commit: "git:commit",
    push: "git:push",
  },
  llm: {
    oneshot: "llm:oneshot",
  },
  i18n: {
    detect: "i18n:detect",
    list: "i18n:list",
    resources: "i18n:resources",
  },
  kernel: {
    install: "kernel:install",
    installDone: "kernel:install-done",
    installProgress: "kernel:install-progress",
    listVersions: "kernel:listVersions",
    status: "kernel:status",
    setCustomCliDir: "kernel:setCustomCliDir",
    fitPiExtensionAvailable: "kernel:fitPiExtensionAvailable",
  },
  misc: {
    openFile: "open-file",
    revealPath: "reveal-path",
  },
  models: {
    get: "models:get",
    set: "models:set",
    list: "models:list",
    getFallbackModel: "models:getFallbackModel",
  },
  notification: {
    show: "notification:show",
  },
  piSettings: {
    get: "pi-settings:get",
    schema: "pi-settings:schema",
    set: "pi-settings:set",
  },
  dshKernel: {
    status: "dsh-kernel:status",
    setCustomCliDir: "dsh-kernel:setCustomCliDir",
    listVersions: "dsh-kernel:listVersions",
    install: "dsh-kernel:install",
  },
  dshModels: {
    get: "dsh-models:get",
    set: "dsh-models:set",
    removeProvider: "dsh-models:removeProvider",
    renameProvider: "dsh-models:renameProvider",
    getDefault: "dsh-models:getDefault",
    setDefault: "dsh-models:setDefault",
    test: "dsh-models:test",
  },

  dshSettings: {
    get: "dsh-settings:get",
    set: "dsh-settings:set",
  },
  kernelModels: {
    list: "kernel-models:list",
    set: "kernel-models:set",
    remove: "kernel-models:remove",
    rename: "kernel-models:rename",
    getDefault: "kernel-models:getDefault",
    setDefault: "kernel-models:setDefault",
    test: "kernel-models:test",
    readConfig: "kernel-models:readConfig",
    saveConfig: "kernel-models:saveConfig",
  },
  kernelConfig: {
    get: "kernel-config:get",
    set: "kernel-config:set",
    fields: "kernel-config:fields",
  },
  kernelLogos: {
    get: "kernel-logos:get",
  },
  plugin: {
    unloaded: "plugin:unloaded",
  },
  plugins: {
    changed: "plugins:changed",
    disable: "plugins:disable",
    enable: "plugins:enable",
    install: "plugins:install",
    list: "plugins:list",
    loadFailed: "plugins:loadFailed",
    reload: "plugins:reload",
    uninstall: "plugins:uninstall",
  },
  prefs: {
    get: "prefs:get",
    set: "prefs:set",
    /** 偏好变更推送(第 22 项):任一客户端 prefs.set 后广播,其他端同步主题/语言等。 */
    changed: "prefs:changed",
  },
  refresh: {
    // 通用刷新信号(main → renderer push):任何操作完成后广播,消费方(会话流)重探
    // 挂载时探测的外部状态。不绑具体资源——tool-gate 安装/内核路径变更等都能发,
    // 消费方订阅列表不随资源数膨胀(design:统一刷新信号,非每资源一条事件)。
    requested: "refresh:requested",
  },
  restart: {
    pendingSessions: "restart:pendingSessions",
    restart: "restart:restart",
    restartAllIdle: "restart:restartAllIdle",
    state: "restart:state",
  },
  session: {
    abort: "session:abort",
    abortBash: "session:abortBash",
    abortRetry: "session:abortRetry",
    clone: "session:clone",
    compact: "session:compact",
    continue: "session:continue",
    copySession: "session:copySession",
    cycleModel: "session:cycleModel",
    cycleThinkingLevel: "session:cycleThinkingLevel",
    delete: "session:delete",
    event: "session:event",
    exportHtml: "session:exportHtml",
    question: "session:question",
    followUp: "session:followUp",
    fork: "session:fork",
    forkFromSession: "session:forkFromSession",
    getForkMessages: "session:getForkMessages",
    getLastAssistantText: "session:getLastAssistantText",
    getCapabilities: "session:getCapabilities",
    getModels: "session:getModels",
    getSnapshot: "session:getSnapshot",
    getStats: "session:getStats",
    getThinkingLevels: "session:getThinkingLevels",
    /** 列表行字段变更推送(归档/置顶/改名/删除后,第 21 项):各端据此重拉会话列表。 */
    headerChanged: "session:headerChanged",
    kernelEvent: "session:kernelEvent",
    open: "session:open",
    prompt: "session:prompt",
    readToolConfig: "session:readToolConfig",
    rename: "session:rename",
    answerQuestion: "session:answerQuestion",
    listTools: "session:listTools",
    runBash: "session:runBash",
    setAutoCompaction: "session:setAutoCompaction",
    setAutoRetry: "session:setAutoRetry",
    setContext: "session:setContext",
    setFollowUpMode: "session:setFollowUpMode",
    setModel: "session:setModel",
    setSteeringMode: "session:setSteeringMode",
    setThinkingLevel: "session:setThinkingLevel",
    snapshot: "session:snapshot",
    start: "session:start",
    steer: "session:steer",
    stop: "session:stop",
    switchKernel: "session:switchKernel",
    sync: "session:sync",
    testModel: "session:testModel",
    updateHeader: "session:updateHeader",
  },
  sessions: {
    list: "sessions:list",
    rawFilePaths: "sessions:rawFilePaths",
    projectStats: "sessions:projectStats",
    getTree: "sessions:getTree",
    bookmark: "sessions:bookmark",
    resume: "sessions:resume",
    deleteBookmark: "sessions:deleteBookmark",
  },
  settings: {
    changed: "settings:changed",
    list: "settings:list",
  },
  skills: {
    changed: "skills:changed",
    getBundled: "skills:getBundled",
    getCapabilities: "skills:getCapabilities",
    list: "skills:list",
    setBundledEnabled: "skills:setBundledEnabled",
    setEnabled: "skills:setEnabled",
    setModelInvocable: "skills:setModelInvocable",
    unwatch: "skills:unwatch",
    watch: "skills:watch",
  },
  slots: {
    mainView: "slots:mainView",
    sidePanel: "slots:sidePanel",
    sidebar: "slots:sidebar",
    titlebar: "slots:titlebar",
  fileActions: "slots:fileActions",
  fileIcons: "slots:fileIcons",
  messageActions: "slots:messageActions",
    blockRenderers: "slots:blockRenderers",
    codeBlockRenderers: "slots:codeBlockRenderers",
    sessionGroupings: "slots:sessionGroupings",
    composerPolicies: "slots:composerPolicies",
    composerAttachments: "slots:composerAttachments",
    composerActions: "slots:composerActions",
    composerStats: "slots:composerStats",
    composerTop: "slots:composerTop",
    settingsGroups: "slots:settingsGroups",
  },
  themes: {
    build: "themes:build",
    list: "themes:list",
    systemChanged: "themes:systemChanged",
  },
  window: {
    minimize: "window:minimize",
    toggleMaximize: "window:toggleMaximize",
    close: "window:close",
    isMaximized: "window:isMaximized",
    isFocused: "window:isFocused",
    maximizedChanged: "window:maximizedChanged",
  },
  /** 远程访问控制面(web-service §18.6)。 */
  remote: {
    status: "remote:status",
    start: "remote:start",
    stop: "remote:stop",
    setPassword: "remote:setPassword",
    refreshPassword: "remote:refreshPassword",
    setLanPasswordEnabled: "remote:setLanPasswordEnabled",
    qr: "remote:qr",
    stateChanged: "remote:stateChanged",
    /** 已连接设备清单(第 23 项)。 */
    connections: "remote:connections",
    /** 踢单个连接(第 23 项)。 */
    kick: "remote:kick",
    /** 踢全部连接(第 24 项)。 */
    kickAll: "remote:kickAll",
    /** 连接增减推送(连上/断开/被踢)。 */
    connectionsChanged: "remote:connectionsChanged",
  },
} as const;

/** 所有合法通道名的联合类型(invoke 应答与 push 推送的总集)。 */
export type IpcChannel =
  { [K in keyof typeof IPC]: (typeof IPC)[K][keyof (typeof IPC)[K]] }[keyof typeof IPC];
