import type { SidepanelStyle, SidepanelStylePreset } from "@pi-desktop/core";

export type { SidepanelStyle, SidepanelStylePreset };

export const SIDEPANEL_STYLES: SidepanelStylePreset[] = [
  {
    id: "default",
    label: "默认",
    vars: {
      "sidepanel.header.py": "8px",
      "sidepanel.header.px": "12px",
      "sidepanel.header.border": "1px solid var(--color-border)",
      "sidepanel.header.bg": "transparent",
      "sidepanel.header.bg.hover": "var(--color-surface)",
      "sidepanel.header.fs": "var(--font-size-sm)",
      "sidepanel.header.fw": "500",
      "sidepanel.content.py": "8px",
      "sidepanel.content.px": "10px",
      "sidepanel.icon.btn.size": "36px",
      "sidepanel.icon.btn.radius": "var(--radius-sm)",
      "sidepanel.icon.btn.bg": "transparent",
      "sidepanel.icon.btn.bg.hover": "var(--color-surface)",
      "sidepanel.icon.btn.bg.active": "var(--color-surface)",
      "sidepanel.icon.btn.border": "none",
      "sidepanel.icon.active.indicator": "3px solid var(--color-primary)",
      "sidepanel.icon.gap": "6px",
      "sidepanel.icon.size": "20px",
      "sidepanel.divider.display": "flex",
      "sidepanel.divider.color": "var(--divider-color)",
      "sidepanel.row.py": "4px",
      "sidepanel.row.px": "8px",
      "sidepanel.row.gap": "6px",
      "sidepanel.row.bg": "transparent",
      "sidepanel.row.bg.hover": "var(--color-surface)",
      "sidepanel.row.bg.active": "var(--color-surface)",
      "sidepanel.row.border": "none",
      "sidepanel.row.border.hover": "none",
      "sidepanel.row.border.active": "none",
      "sidepanel.row.radius": "var(--radius-sm)",
      "sidepanel.row.shadow": "none",
      "sidepanel.row.shadow.active": "none",
      "sidepanel.toolbar.py": "4px",
      "sidepanel.toolbar.px": "8px",
      "sidepanel.toolbar.gap": "6px",
      "sidepanel.toolbar.border": "none",
      "sidepanel.toolbar.bg": "transparent",
      "sidepanel.btn.size": "22px",
      "sidepanel.btn.radius": "var(--radius-sm)",
      "sidepanel.btn.border": "none",
      "sidepanel.btn.bg": "transparent",
      "sidepanel.btn.bg.hover": "var(--color-surface)",
      "sidepanel.btn.icon.size": "14px",
      "sidepanel.input.py": "4px",
      "sidepanel.input.px": "8px",
      "sidepanel.input.border": "1px solid var(--color-border)",
      "sidepanel.input.border.focus": "1px solid var(--color-primary)",
      "sidepanel.input.radius": "var(--radius-sm)",
      "sidepanel.input.bg": "var(--color-bg)",
      "sidepanel.card.py": "12px",
      "sidepanel.card.px": "12px",
      "sidepanel.card.border": "1px solid var(--color-border)",
      "sidepanel.card.radius": "var(--radius-md)",
      "sidepanel.card.shadow": "none",
      "sidepanel.card.bg": "var(--color-surface)",
      "sidepanel.section.fs": "var(--font-size-sm)",
      "sidepanel.section.py": "6px",
      "sidepanel.section.px": "8px",
      "sidepanel.section.weight": "600",
      "sidepanel.stat.py": "4px",
      "sidepanel.glass.blur": "none",
    },
  },
  {
    id: "card",
    label: "卡片",
    vars: {
      "sidepanel.header.py": "10px",
      "sidepanel.header.px": "14px",
      "sidepanel.header.border": "none",
      "sidepanel.header.bg": "transparent",
      "sidepanel.header.bg.hover": "var(--color-surface)",
      "sidepanel.header.fs": "var(--font-size-sm)",
      "sidepanel.header.fw": "600",
      "sidepanel.content.py": "10px",
      "sidepanel.content.px": "12px",
      "sidepanel.icon.btn.size": "36px",
      "sidepanel.icon.btn.radius": "var(--radius-md)",
      "sidepanel.icon.btn.bg": "transparent",
      "sidepanel.icon.btn.bg.hover": "var(--color-surface)",
      "sidepanel.icon.btn.bg.active": "var(--color-surface)",
      "sidepanel.icon.btn.border": "1px solid var(--color-border)",
      "sidepanel.icon.active.indicator": "none",
      "sidepanel.icon.gap": "8px",
      "sidepanel.icon.size": "20px",
      "sidepanel.divider.display": "none",
      "sidepanel.divider.color": "var(--divider-color)",
      "sidepanel.row.py": "10px",
      "sidepanel.row.px": "12px",
      "sidepanel.row.gap": "8px",
      "sidepanel.row.bg": "transparent",
      "sidepanel.row.bg.hover": "var(--color-surface)",
      "sidepanel.row.bg.active": "var(--color-surface)",
      "sidepanel.row.border": "1px solid var(--color-border)",
      "sidepanel.row.border.hover": "1px solid color-mix(in srgb, var(--color-border) 70%, var(--color-primary) 30%)",
      "sidepanel.row.border.active": "1px solid var(--color-primary)",
      "sidepanel.row.radius": "var(--radius-lg)",
      "sidepanel.row.shadow": "var(--shadow-sm)",
      "sidepanel.row.shadow.active": "var(--shadow-md)",
      "sidepanel.toolbar.py": "6px",
      "sidepanel.toolbar.px": "10px",
      "sidepanel.toolbar.gap": "8px",
      "sidepanel.toolbar.border": "none",
      "sidepanel.toolbar.bg": "transparent",
      "sidepanel.btn.size": "26px",
      "sidepanel.btn.radius": "var(--radius-md)",
      "sidepanel.btn.border": "1px solid var(--color-border)",
      "sidepanel.btn.bg": "transparent",
      "sidepanel.btn.bg.hover": "var(--color-surface)",
      "sidepanel.btn.icon.size": "15px",
      "sidepanel.input.py": "6px",
      "sidepanel.input.px": "10px",
      "sidepanel.input.border": "1px solid var(--color-border)",
      "sidepanel.input.border.focus": "1px solid var(--color-primary)",
      "sidepanel.input.radius": "var(--radius-md)",
      "sidepanel.input.bg": "var(--color-bg)",
      "sidepanel.card.py": "14px",
      "sidepanel.card.px": "14px",
      "sidepanel.card.border": "1px solid var(--color-border)",
      "sidepanel.card.radius": "var(--radius-lg)",
      "sidepanel.card.shadow": "var(--shadow-sm)",
      "sidepanel.card.bg": "var(--color-surface)",
      "sidepanel.section.fs": "11px",
      "sidepanel.section.py": "10px",
      "sidepanel.section.px": "10px",
      "sidepanel.section.weight": "600",
      "sidepanel.stat.py": "8px",
      "sidepanel.glass.blur": "none",
    },
  },
  {
    id: "minimal",
    label: "极简",
    vars: {
      "sidepanel.header.py": "6px",
      "sidepanel.header.px": "12px",
      "sidepanel.header.border": "none",
      "sidepanel.header.bg": "transparent",
      "sidepanel.header.bg.hover": "transparent",
      "sidepanel.header.fs": "var(--font-size-sm)",
      "sidepanel.header.fw": "400",
      "sidepanel.content.py": "4px",
      "sidepanel.content.px": "8px",
      "sidepanel.icon.btn.size": "32px",
      "sidepanel.icon.btn.radius": "0px",
      "sidepanel.icon.btn.bg": "transparent",
      "sidepanel.icon.btn.bg.hover": "transparent",
      "sidepanel.icon.btn.bg.active": "var(--color-surface)",
      "sidepanel.icon.btn.border": "none",
      "sidepanel.icon.active.indicator": "3px solid var(--color-primary)",
      "sidepanel.icon.gap": "2px",
      "sidepanel.icon.size": "18px",
      "sidepanel.divider.display": "none",
      "sidepanel.divider.color": "var(--divider-color)",
      "sidepanel.row.py": "6px",
      "sidepanel.row.px": "10px",
      "sidepanel.row.gap": "2px",
      "sidepanel.row.bg": "transparent",
      "sidepanel.row.bg.hover": "transparent",
      "sidepanel.row.bg.active": "var(--color-surface)",
      "sidepanel.row.border": "none",
      "sidepanel.row.border.hover": "none",
      "sidepanel.row.border.active": "none",
      "sidepanel.row.radius": "0px",
      "sidepanel.row.shadow": "none",
      "sidepanel.row.shadow.active": "inset 3px 0 0 var(--color-primary)",
      "sidepanel.toolbar.py": "4px",
      "sidepanel.toolbar.px": "8px",
      "sidepanel.toolbar.gap": "4px",
      "sidepanel.toolbar.border": "none",
      "sidepanel.toolbar.bg": "transparent",
      "sidepanel.btn.size": "20px",
      "sidepanel.btn.radius": "0px",
      "sidepanel.btn.border": "none",
      "sidepanel.btn.bg": "transparent",
      "sidepanel.btn.bg.hover": "var(--color-surface)",
      "sidepanel.btn.icon.size": "15px",
      "sidepanel.input.py": "4px",
      "sidepanel.input.px": "0px",
      "sidepanel.input.border": "none",
      "sidepanel.input.border.focus": "1px solid var(--color-primary)",
      "sidepanel.input.radius": "0px",
      "sidepanel.input.bg": "transparent",
      "sidepanel.card.py": "8px",
      "sidepanel.card.px": "10px",
      "sidepanel.card.border": "none",
      "sidepanel.card.radius": "0px",
      "sidepanel.card.shadow": "none",
      "sidepanel.card.bg": "var(--color-surface)",
      "sidepanel.section.fs": "11px",
      "sidepanel.section.py": "12px",
      "sidepanel.section.px": "4px",
      "sidepanel.section.weight": "400",
      "sidepanel.stat.py": "4px",
      "sidepanel.glass.blur": "none",
    },
  },
  {
    id: "outline",
    label: "描边",
    vars: {
      "sidepanel.header.py": "8px",
      "sidepanel.header.px": "12px",
      "sidepanel.header.border": "1px dashed var(--color-border)",
      "sidepanel.header.bg": "transparent",
      "sidepanel.header.bg.hover": "transparent",
      "sidepanel.header.fs": "var(--font-size-sm)",
      "sidepanel.header.fw": "500",
      "sidepanel.content.py": "8px",
      "sidepanel.content.px": "10px",
      "sidepanel.icon.btn.size": "36px",
      "sidepanel.icon.btn.radius": "var(--radius-sm)",
      "sidepanel.icon.btn.bg": "transparent",
      "sidepanel.icon.btn.bg.hover": "transparent",
      "sidepanel.icon.btn.bg.active": "var(--color-surface)",
      "sidepanel.icon.btn.border": "1px dashed var(--color-border)",
      "sidepanel.icon.active.indicator": "3px solid var(--color-primary)",
      "sidepanel.icon.gap": "6px",
      "sidepanel.icon.size": "20px",
      "sidepanel.divider.display": "flex",
      "sidepanel.divider.color": "var(--color-border)",
      "sidepanel.row.py": "8px",
      "sidepanel.row.px": "10px",
      "sidepanel.row.gap": "6px",
      "sidepanel.row.bg": "transparent",
      "sidepanel.row.bg.hover": "transparent",
      "sidepanel.row.bg.active": "var(--color-surface)",
      "sidepanel.row.border": "1px dashed var(--color-border)",
      "sidepanel.row.border.hover": "1px dashed var(--color-primary)",
      "sidepanel.row.border.active": "1px solid var(--color-primary)",
      "sidepanel.row.radius": "var(--radius-sm)",
      "sidepanel.row.shadow": "none",
      "sidepanel.row.shadow.active": "none",
      "sidepanel.toolbar.py": "6px",
      "sidepanel.toolbar.px": "8px",
      "sidepanel.toolbar.gap": "6px",
      "sidepanel.toolbar.border": "1px dashed var(--color-border)",
      "sidepanel.toolbar.bg": "transparent",
      "sidepanel.btn.size": "22px",
      "sidepanel.btn.radius": "var(--radius-sm)",
      "sidepanel.btn.border": "1px dashed var(--color-border)",
      "sidepanel.btn.bg": "transparent",
      "sidepanel.btn.bg.hover": "transparent",
      "sidepanel.btn.icon.size": "14px",
      "sidepanel.input.py": "4px",
      "sidepanel.input.px": "8px",
      "sidepanel.input.border": "1px dashed var(--color-border)",
      "sidepanel.input.border.focus": "1px solid var(--color-primary)",
      "sidepanel.input.radius": "var(--radius-sm)",
      "sidepanel.input.bg": "transparent",
      "sidepanel.card.py": "10px",
      "sidepanel.card.px": "10px",
      "sidepanel.card.border": "1px dashed var(--color-border)",
      "sidepanel.card.radius": "var(--radius-sm)",
      "sidepanel.card.shadow": "none",
      "sidepanel.card.bg": "transparent",
      "sidepanel.section.fs": "11px",
      "sidepanel.section.py": "8px",
      "sidepanel.section.px": "8px",
      "sidepanel.section.weight": "600",
      "sidepanel.stat.py": "6px",
      "sidepanel.glass.blur": "none",
    },
  },
  {
    id: "glass",
    label: "玻璃",
    vars: {
      "sidepanel.header.py": "8px",
      "sidepanel.header.px": "12px",
      "sidepanel.header.border": "1px solid color-mix(in srgb, var(--color-border) 60%, transparent)",
      "sidepanel.header.bg": "color-mix(in srgb, var(--color-surface) 30%, transparent)",
      "sidepanel.header.bg.hover": "color-mix(in srgb, var(--color-surface) 50%, transparent)",
      "sidepanel.header.fs": "var(--font-size-sm)",
      "sidepanel.header.fw": "500",
      "sidepanel.content.py": "8px",
      "sidepanel.content.px": "10px",
      "sidepanel.icon.btn.size": "36px",
      "sidepanel.icon.btn.radius": "var(--radius-md)",
      "sidepanel.icon.btn.bg": "color-mix(in srgb, var(--color-surface) 30%, transparent)",
      "sidepanel.icon.btn.bg.hover": "color-mix(in srgb, var(--color-surface) 50%, transparent)",
      "sidepanel.icon.btn.bg.active": "color-mix(in srgb, var(--color-primary) 15%, transparent)",
      "sidepanel.icon.btn.border": "1px solid color-mix(in srgb, var(--color-border) 50%, transparent)",
      "sidepanel.icon.active.indicator": "3px solid var(--color-primary)",
      "sidepanel.icon.gap": "6px",
      "sidepanel.icon.size": "20px",
      "sidepanel.divider.display": "none",
      "sidepanel.divider.color": "color-mix(in srgb, var(--color-border) 40%, transparent)",
      "sidepanel.row.py": "8px",
      "sidepanel.row.px": "10px",
      "sidepanel.row.gap": "6px",
      "sidepanel.row.bg": "color-mix(in srgb, var(--color-surface) 40%, transparent)",
      "sidepanel.row.bg.hover": "color-mix(in srgb, var(--color-surface) 60%, transparent)",
      "sidepanel.row.bg.active": "color-mix(in srgb, var(--color-primary) 15%, transparent)",
      "sidepanel.row.border": "1px solid color-mix(in srgb, var(--color-border) 40%, transparent)",
      "sidepanel.row.border.hover": "1px solid color-mix(in srgb, var(--color-primary) 40%, transparent)",
      "sidepanel.row.border.active": "1px solid color-mix(in srgb, var(--color-primary) 60%, transparent)",
      "sidepanel.row.radius": "var(--radius-md)",
      "sidepanel.row.shadow": "0 1px 4px rgba(0,0,0,0.1)",
      "sidepanel.row.shadow.active": "0 2px 12px rgba(0,0,0,0.18)",
      "sidepanel.toolbar.py": "6px",
      "sidepanel.toolbar.px": "10px",
      "sidepanel.toolbar.gap": "6px",
      "sidepanel.toolbar.border": "1px solid color-mix(in srgb, var(--color-border) 40%, transparent)",
      "sidepanel.toolbar.bg": "color-mix(in srgb, var(--color-surface) 20%, transparent)",
      "sidepanel.btn.size": "24px",
      "sidepanel.btn.radius": "var(--radius-sm)",
      "sidepanel.btn.border": "1px solid color-mix(in srgb, var(--color-border) 40%, transparent)",
      "sidepanel.btn.bg": "color-mix(in srgb, var(--color-surface) 30%, transparent)",
      "sidepanel.btn.bg.hover": "color-mix(in srgb, var(--color-surface) 50%, transparent)",
      "sidepanel.btn.icon.size": "14px",
      "sidepanel.input.py": "6px",
      "sidepanel.input.px": "10px",
      "sidepanel.input.border": "1px solid color-mix(in srgb, var(--color-border) 40%, transparent)",
      "sidepanel.input.border.focus": "1px solid color-mix(in srgb, var(--color-primary) 60%, transparent)",
      "sidepanel.input.radius": "var(--radius-sm)",
      "sidepanel.input.bg": "color-mix(in srgb, var(--color-surface) 20%, transparent)",
      "sidepanel.card.py": "12px",
      "sidepanel.card.px": "12px",
      "sidepanel.card.border": "1px solid color-mix(in srgb, var(--color-border) 40%, transparent)",
      "sidepanel.card.radius": "var(--radius-md)",
      "sidepanel.card.shadow": "0 2px 8px rgba(0,0,0,0.12)",
      "sidepanel.card.bg": "color-mix(in srgb, var(--color-surface) 30%, transparent)",
      "sidepanel.section.fs": "var(--font-size-sm)",
      "sidepanel.section.py": "8px",
      "sidepanel.section.px": "8px",
      "sidepanel.section.weight": "600",
      "sidepanel.stat.py": "6px",
      "sidepanel.glass.blur": "blur(8px)",
    },
  },
];

export const SIDEPANEL_STYLE_MAP: Record<string, SidepanelStylePreset> = Object.fromEntries(
  SIDEPANEL_STYLES.map((s) => [s.id, s]),
);
