export type SidebarStyle = "default" | "card" | "minimal" | "outline" | "glass";

export interface SidebarStylePreset {
  id: SidebarStyle;
  label: string;
  vars: Record<string, string>;
}

export const SIDEBAR_STYLES: SidebarStylePreset[] = [
  {
    id: "default",
    label: "默认",
    vars: {
      "--sidebar-row-gap": "6px",
      "--sidebar-row-py": "10px",
      "--sidebar-row-px": "10px",
      "--sidebar-icon-size": "14px",
      "--sidebar-icon-box": "20px",
      "--sidebar-section-fs": "12px",
      "--sidebar-section-pt": "6px",
      "--sidebar-section-pb": "6px",
      "--sidebar-arrow-display": "inline-flex",
      "--sidebar-divider-display": "flex",
      "--sidebar-row-bg": "transparent",
      "--sidebar-row-bg-hover": "var(--color-surface)",
      "--sidebar-row-bg-active": "var(--color-surface)",
      "--sidebar-row-border": "none",
      "--sidebar-row-border-hover": "none",
      "--sidebar-row-border-active": "none",
      "--sidebar-row-radius": "var(--radius-md)",
      "--sidebar-row-shadow": "none",
      "--sidebar-row-shadow-active": "none",
    },
  },
  {
    id: "card",
    label: "卡片",
    vars: {
      "--sidebar-row-gap": "8px",
      "--sidebar-row-py": "10px",
      "--sidebar-row-px": "12px",
      "--sidebar-icon-size": "16px",
      "--sidebar-icon-box": "28px",
      "--sidebar-section-fs": "11px",
      "--sidebar-section-pt": "16px",
      "--sidebar-section-pb": "6px",
      "--sidebar-arrow-display": "none",
      "--sidebar-divider-display": "none",
      "--sidebar-row-bg": "transparent",
      "--sidebar-row-bg-hover": "var(--color-surface)",
      "--sidebar-row-bg-active": "var(--color-surface)",
      "--sidebar-row-border": "1px solid var(--color-border)",
      "--sidebar-row-border-hover": "1px solid var(--color-border)",
      "--sidebar-row-border-active": "1px solid var(--color-primary)",
      "--sidebar-row-radius": "var(--radius-lg)",
      "--sidebar-row-shadow": "var(--shadow-sm)",
      "--sidebar-row-shadow-active": "var(--shadow-md)",
    },
  },
  {
    id: "minimal",
    label: "极简",
    vars: {
      "--sidebar-row-gap": "2px",
      "--sidebar-row-py": "8px",
      "--sidebar-row-px": "12px",
      "--sidebar-icon-size": "15px",
      "--sidebar-icon-box": "20px",
      "--sidebar-section-fs": "11px",
      "--sidebar-section-pt": "16px",
      "--sidebar-section-pb": "4px",
      "--sidebar-arrow-display": "none",
      "--sidebar-divider-display": "none",
      "--sidebar-row-bg": "transparent",
      "--sidebar-row-bg-hover": "transparent",
      "--sidebar-row-bg-active": "var(--color-surface)",
      "--sidebar-row-border": "none",
      "--sidebar-row-border-hover": "none",
      "--sidebar-row-border-active": "none",
      "--sidebar-row-radius": "0px",
      "--sidebar-row-shadow": "none",
      "--sidebar-row-shadow-active": "inset 3px 0 0 var(--color-primary)",
    },
  },
  {
    id: "outline",
    label: "描边",
    vars: {
      "--sidebar-row-gap": "6px",
      "--sidebar-row-py": "10px",
      "--sidebar-row-px": "12px",
      "--sidebar-icon-size": "14px",
      "--sidebar-icon-box": "20px",
      "--sidebar-section-fs": "11px",
      "--sidebar-section-pt": "12px",
      "--sidebar-section-pb": "6px",
      "--sidebar-arrow-display": "inline-flex",
      "--sidebar-divider-display": "flex",
      "--sidebar-row-bg": "transparent",
      "--sidebar-row-bg-hover": "transparent",
      "--sidebar-row-bg-active": "var(--color-surface)",
      "--sidebar-row-border": "1px dashed var(--color-border)",
      "--sidebar-row-border-hover": "1px dashed var(--color-primary)",
      "--sidebar-row-border-active": "1px solid var(--color-primary)",
      "--sidebar-row-radius": "var(--radius-sm)",
      "--sidebar-row-shadow": "none",
      "--sidebar-row-shadow-active": "none",
    },
  },
  {
    id: "glass",
    label: "玻璃",
    vars: {
      "--sidebar-row-gap": "6px",
      "--sidebar-row-py": "10px",
      "--sidebar-row-px": "10px",
      "--sidebar-icon-size": "14px",
      "--sidebar-icon-box": "24px",
      "--sidebar-section-fs": "12px",
      "--sidebar-section-pt": "10px",
      "--sidebar-section-pb": "6px",
      "--sidebar-arrow-display": "inline-flex",
      "--sidebar-divider-display": "none",
      "--sidebar-row-bg": "color-mix(in srgb, var(--color-surface) 50%, transparent)",
      "--sidebar-row-bg-hover": "color-mix(in srgb, var(--color-surface) 70%, transparent)",
      "--sidebar-row-bg-active": "color-mix(in srgb, var(--color-primary) 15%, transparent)",
      "--sidebar-row-border": "1px solid color-mix(in srgb, var(--color-border) 60%, transparent)",
      "--sidebar-row-border-hover": "1px solid color-mix(in srgb, var(--color-primary) 40%, transparent)",
      "--sidebar-row-border-active": "1px solid color-mix(in srgb, var(--color-primary) 60%, transparent)",
      "--sidebar-row-radius": "var(--radius-md)",
      "--sidebar-row-shadow": "0 2px 8px rgba(0,0,0,0.15)",
      "--sidebar-row-shadow-active": "0 4px 16px rgba(0,0,0,0.25)",
    },
  },
];

export const SIDEBAR_STYLE_MAP: Record<string, SidebarStylePreset> = Object.fromEntries(
  SIDEBAR_STYLES.map((s) => [s.id, s]),
);
